language: node_js
node_js:
  - "node"
services: 
  - mongodb
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: cd back && npm install && npm test-quick